### ISSUE TITLE
Socket.io werkt niet

### ISSUE THREAD

**Issue by Harsves** [fdnd-task/pleasurable-ui#4]
Ik krijg de volgende errors:

<img width="480" alt="Schermafbeelding 2023-05-16 om 15 27 29" src="https://github.com/fdnd-task/connecting-people-realtime-web-app/assets/112931845/8d401537-6cba-4fc3-a4dc-08332f4505d3">

Ik ben al de hele dag bezig om het op te lossen maar dat is mij tot nu toe nog niet gelukt. Ik ben naar Pip gegaan om te vragen of ze mij kon helpen maar ook zij kwam er niet uit.

**Comment by KoopReynders** [comment]
history

**Comment by KoopReynders** [comment]
history
